apiVersion: v1
kind: Service
metadata:
  name: catalogue-example
  namespace: roboshop
spec:
  selector:
    name: catalogue
    tier: app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
